//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Mediator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Mediator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped delegates have to be async..
        /// </summary>
        public static string AsyncDelegateRequiredException {
            get {
                return ResourceManager.GetString("AsyncDelegateRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the constructor for type &apos;{0}&apos;..
        /// </summary>
        public static string ContextConstructorException {
            get {
                return ResourceManager.GetString("ContextConstructorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a delegate mapped to message type &apos;{0}&apos;..
        /// </summary>
        public static string DelegateAlreadyMappedException {
            get {
                return ResourceManager.GetString("DelegateAlreadyMappedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant with type name &apos;{0}&apos; does not implment `IParticipant&lt;T&gt;`..
        /// </summary>
        public static string InvalidParticipantTypeException {
            get {
                return ResourceManager.GetString("InvalidParticipantTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a participant for type &apos;{0}&apos;..
        /// </summary>
        public static string MissingParticipantException {
            get {
                return ResourceManager.GetString("MissingParticipantException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not implement an `IParticipant&lt;&gt;` interfrace..
        /// </summary>
        public static string ParticipantInterfaceMissingException {
            get {
                return ResourceManager.GetString("ParticipantInterfaceMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate must contain at least one parameter.  The first parameter must be the message..
        /// </summary>
        public static string ParticipantTypeException {
            get {
                return ResourceManager.GetString("ParticipantTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have the required ProcessMessage method for message type &apos;{1}&apos;..
        /// </summary>
        public static string ProcessMessageMethodMissingException {
            get {
                return ResourceManager.GetString("ProcessMessageMethodMissingException", resourceCulture);
            }
        }
    }
}
